### ISSUE TITLE
Editable attributes for groups

### ISSUE THREAD

**Issue by canitzp** [wheelybird/ldap-user-manager#103]
I currently try to find a solution for our old and unreliable ldap server and want to use this, but after testing for some time I found out that is is possible to set attributes to users, but there is no way (with the webinterface) to set any group attributes. In my case I need to set the 'gidNumber' of each groups.
It also would be nice to have some kind of way to add additional objectclasses or attributes to groups, like it is possible for users.

I'm using the next_release container.

For now I can set the gidNumber per terminal, but this is not a fine solution.

**Comment by wheelybird** [comment]
Hi.  I haven't implemented the ability to add group attributes as the code around creating/updating the groups isn't very flexible because of the schema detection.  I'm undecided as to whether I _should_ implement that considering this was always supposed to be a simple user manager.  I do agree that the gidNumber should be editable though, so I'll add that into the next release.

**Comment by canitzp** [comment]
Okay thank you, adding the ability to edit the gidNumber is very good.
I also noticed something else. The group names are set to have at least 3 characters by your manager, but this isn't a necessity by ldap itself. While migration I had to add groups with only two character names via the terminal.

**Comment by wheelybird** [comment]
Both group and usernames are validated with `USERNAME_REGEX` which tries to keep things POSIXy.  You can disable that by setting  `ENFORCE_SAFE_SYSTEM_NAMES` to false or by changing the regex.
