### ISSUE TITLE
GID is missing when creating a new account with SHOW_POSIX_ATTRIBUTES

### ISSUE THREAD

**Issue by dr-waterstorm** [wheelybird/ldap-user-manager#177]
**Version**
Latest container from docker.io ([v.18](https://github.com/wheelybird/ldap-user-manager/tree/v.18))

**Describe the bug**
I've enabled `SHOW_POSIX_ATTRIBUTES` as we are using the LDAP to login to our Linux servers.
When editing an existing account, this works perfectly fine and shows me all important fields (in our case we need to set: Home, Shell and GID, as those need to be adjusted for our server setup to be able to login).

However when creating a new account, the GID field is missing:
![image](https://user-images.githubusercontent.com/11409264/194822876-8197a39d-ed7e-4628-b627-67864f1b0d25.png)

I can edit Home and Shell, but I cannot set the GID. It will automatically set GID to 2001.
So the workflow when creating a new user right now, is to create the user and then edit it to be able to set the GID. This would be way easier when the field would be available directly when creating a new user.

Thank you!

**Comment by BrianLycett-Which** [comment]
Hi.  The default setting is to hide some Posix fields in order to simplify the interface.  Set `SHOW_POSIX_ATTRIBUTES=true` to override that (https://github.com/wheelybird/ldap-user-manager#interface-customisation).  I think the bug here is that those attributes should be hidden on the edit page if `SHOW_POSIX_ATTRIBUTES` _isn't_ true.

**Comment by wheelybird** [comment]
Hi. The default setting is to hide some Posix fields in order to simplify the interface. Set `SHOW_POSIX_ATTRIBUTES=true` to override that (https://github.com/wheelybird/ldap-user-manager#interface-customisation). I think the bug here is that those attributes should be hidden on the edit page if `SHOW_POSIX_ATTRIBUTES` _isn't_ true.

**Comment by dr-waterstorm** [comment]
Yes, that is set to true, which works in "edit mode", but not in "account creation mode"

**Comment by wheelybird** [comment]
Sorry, I missed that you'd set it.  I'll take a look.

**Comment by dr-waterstorm** [comment]
thank you :)

**Comment by wheelybird** [comment]
That should be fixed now with the latest version (wheelybird/ldap-user-manager:v1.9)
