### ISSUE TITLE
How to configure when running using apache + php?

### ISSUE THREAD

**Issue by stodge** [wheelybird/ldap-user-manager#26]
If I setup a website for ldap-user-manager using apache + php, but I don't use docker, do I still configure it using environment variables or could I change config.inc.php? I assume I can run it using apache + php?

**Comment by wheelybird** [comment]
Yes, it's possible to run without using Docker.  You could configure the defaults in config.inc.php, but it's probably better to configure it using environmental variables so that you can run a `git pull` without conflicts.  For example, if you're using a Debian-based distribution you can add them to `/etc/apache2/envvars`.

**Comment by stodge** [comment]
Thanks. It works by adding the env values into the Apache configuration file:

```
<VirtualHost *:80>
...
SetEnv LDAP_URI "ldap://localhost"
...
</VirtualHost>
```
