### ISSUE TITLE
non tls config gives starttls error

### ISSUE THREAD

**Issue by cyberb** [wheelybird/ldap-user-manager#56]
I am getting this warning in the log:

```
Dec 27 13:18:45 9196617a3939 [1348]: Failed to start STARTTLS connection to ldap://localhost: Protocol error
```

Config (php-fpm):
```
env[LDAP_URI] = 'ldap://localhost'
env[LDAP_REQUIRE_STARTTLS] = 'FALSE'
```

This code seems suspicious:

```
if (!preg_match("/^ldaps:/", $LDAP['uri'])) {

  $tls_result = @ ldap_start_tls($ldap_connection);
```

**Comment by wheelybird** [comment]
Hi.  I don't understand why you think that code is suspicious.  LDAPS is different from STARTTLS connections, and that what that code is checking for.  The `LDAP_REQUIRE_STARTTLS` variable dictates whether an insecure connection to an LDAP server will be _allowed_  - it's attempted regardless, hence the warning message.  If `LDAP_REQUIRE_STARTTLS` is `TRUE` and your server doesn't support STARTTLS then the user manager will drop the connection and throw an error.

**Comment by cyberb** [comment]
>  LDAPS is different from STARTTLS 

Right, forgot about that.

> it's attempted regardless

Is this normal? Should you not try starttls if it is not required or is it not possible? Warnings are not helping to investigate my config problems.

**Comment by wheelybird** [comment]
It is quite normal.  I'm trying to make it hard _not_ to use STARTTLS because we don't want people's passwords flying around in plain text.  There's no reason not to _try_ using in and it needs to be a considered decision by the admin that if STARTTLS isn't supported by the server that the connection can still go ahead.
If you're having issues with your connection then try using `LDAP_VERBOSE_CONNECTION_LOGS`.  You can use that to get very detailed information on what's happening with the connection.
