### ISSUE TITLE
Invalid auto-generated certificate - ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by stodge** [wheelybird/ldap-user-manager#62]
I set `NO_HTTPS=FALSE` to let the SSL certificate be automatically generated for me. When I access LUM via a browser, the connection isn't secure and the certificate is shown as invalid. I don't know if this is relevant but the IP is showing as 127.0.0.1:

```
cat /srv/lum/ssl/conf
subjectAltName = DNS:auth.xxxx.xxx,IP:127.0.0.1
extendedKeyUsage = serverAuth
```

Does this matter? Should it be the IP of the hosting server? I'm running in a Docker container.

Thanks

**Comment by stodge** [comment]
I checked the code and the IP is hard coded so I assume this isn't the problem.

**Comment by wheelybird** [comment]
All browsers will mark self-signed certificates as invalid because there's no corresponding certificate authority for them.  You just need to skip past the warning.
To avoid this you can use your own certificates by bind-mounting the directory they're in into the container as described here: https://github.com/wheelybird/ldap-user-manager#ssl-setup

The value of self-signed certificates is that you're still able to have your traffic encrypted even if you don't have "proper" certificates and as you set up the server yourself you know you can trust the certificates even if the browser doesn't.
