### ISSUE TITLE
Create RO user for binddn?

### ISSUE THREAD

**Issue by pwFoo** [wheelybird/ldap-user-manager#67]
Hi,

I use LUM with openldap and it works fine for users and groups with memberof support. But how to create a binddn user with read only permissions with LUM?
Wan't use a admin user with RW access to the ldap for user verification and haven't found a way to set user permissions within LUM (or phpldapadmin).

Thanks for LUM as easy user and group management! 👍

**Comment by pwFoo** [comment]
Some more requirements for that RO user

- read only permissions to read all or just users of a given group
- user shouldn't visible as member of that group
- manage bind user as a third tab (users, groups, bind users)?

**Comment by wheelybird** [comment]
Hi.  Thanks for the suggestion.  I think that creating read-only bind users is beyond the remit of this application - the aim of the application is to simplify setting up users and groups _within_ LDAP for use by other applications (e.g. Unix logins, Jenkins servers and so on) rather than configuring the LDAP directory itself.
I think you're saying that you don't want to use a RW user in these other applications when authenticating users?  If you're using osixia/docker-openldap then you can create a read-only user when setting up the directory with the LDAP_READONLY_USER option.
Alternatively you should be able to use anonymous binding in order to authenticate users - this application uses that when users log in, so if you've successfully logged in your LDAP directory allows anonymous binding.

**Comment by pwFoo** [comment]
Hi,
thanks for your answer. So maybe LDAP_READONLY_USER could be ok. 
Is it possible to add one (or more) LDAP_READONLY_USER during re-deployment to a already installed openldap?
And will a read only user allowed to read / verify existing users?

Maybe dumb questions, but I'm new with (open)ldap...

**Comment by wheelybird** [comment]
Creating the read-only user is only possible during the initial setup phase of using the osixia/docker-openldap image.  However you can still set up a read-only user yourself using the traditional LDAP utilities, but that's a non-trivial thing as it goes into the realms of creating access control lists and the likes.
Anonymous binding is probably the best approach here.  If the application you're trying to set up for LDAP authentication has fields for the bind DN and bind password, leave them blank and it will probably try and use anonymous binding.

**Comment by pwFoo** [comment]
Ok, I'll try to leave the fields blank and test if it works that way. Thanks!

Because my ldap is small at the moment... 
If I reinstall openldap the read only user has the needed permissions to be used as bindn (for all users)?

**Comment by wheelybird** [comment]
I haven't personally tested setting up the read-only LDAP user with osixia/docker-openldap.  Their documentation doesn't give details on what that user can access, but I would guess that it's intended for the scenario you're describing.

**Comment by pwFoo** [comment]
Ok, thanks!
Because it isn't related to your LUM I close the issue.
