### ISSUE TITLE
Customize field labels

### ISSUE THREAD

**Issue by cyberb** [wheelybird/ldap-user-manager#74]
Is it possible to provide a custom.name for fields?
For example I would like to rename "Common name" to "Username".

**Comment by wheelybird** [comment]
Yes.  You can override the label in the same way you add extra attributes as described here:  https://github.com/wheelybird/ldap-user-manager/tree/use_other_attributes#extra-objectclasses-and-attributes  The attribute is 'cn'.
You'll need to pull the latest version of that branch as there were tag parsing errors that I've since fixed.

**Comment by cyberb** [comment]
Cool, thanks
